name: oPODSync
version: "0.9.3"
slug: opodsync
description: GPodder compatible sync server for podcasts
startup: application
boot: auto
url: "https://fossil.kd2.org/opodsync"

arch:
  - amd64
  - armv7
  - aarch64

ingress: false
webui: "http://[HOST]:[PORT:8080]/"
ports:
  "8080/tcp": 8080
ports_description:
  "8080/tcp": "Web UI"
map:
  - /var/www/server:rw

schema: {}
options: {}
init: false
